runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: B4

basic_scaling:
  max_instances: 5 
  # idle_timeout: 10m

handlers:
- url: /recycool
  script: auto

- url: /recycool/.*
  script: auto
  
- url: /static
  static_dir: static